In [17]:
import numpy as np
arr=[[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]]
arr=np.array(arr)
print(arr)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


Getting the shape of a numpy Array 

In [18]:
arr.shape()

(3, 5)

Reshaping an array

In [31]:
arr=arr.reshape(5,3) 
print(arr)    #multiplication of arguements should be equal to the number of elements in the array

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]]


Indexing of an array

In [32]:
arr[1:3,1:]        #arr[row_start:row_end,column_start:column_end]

array([[5, 6],
       [8, 9]])

Create array based on start and end points

In [33]:
arr=np.arange(1,10,2)    #np.arange(start,end,step)
print(arr)

[1 2 3 4 5 6 7 8 9]


In [36]:
arr=np.linspace(2,30,20)  #np.linspace(start,end,no_of_points)
print(arr)

[ 2.          3.47368421  4.94736842  6.42105263  7.89473684  9.36842105
 10.84210526 12.31578947 13.78947368 15.26315789 16.73684211 18.21052632
 19.68421053 21.15789474 22.63157895 24.10526316 25.57894737 27.05263158
 28.52631579 30.        ]


Important for EDA

In [40]:
#comparing which values in an array are greater than 5
val=5
print(arr>5)

#check which values
print(arr[arr>5])

[False False False  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True]
[ 6.42105263  7.89473684  9.36842105 10.84210526 12.31578947 13.78947368
 15.26315789 16.73684211 18.21052632 19.68421053 21.15789474 22.63157895
 24.10526316 25.57894737 27.05263158 28.52631579 30.        ]


In [38]:
#operations on each element of an array
print(arr*2)

[ 4.          6.94736842  9.89473684 12.84210526 15.78947368 18.73684211
 21.68421053 24.63157895 27.57894737 30.52631579 33.47368421 36.42105263
 39.36842105 42.31578947 45.26315789 48.21052632 51.15789474 54.10526316
 57.05263158 60.        ]


Special methods of creating arrays

In [43]:
#np.ones((row,column),dtype)
zero=np.zeros((2,4),dtype=int)         
one=np.ones((2,4),dtype=int)         #default dtype is float
print(one,zero,sep="\n")  

[[1 1 1 1]
 [1 1 1 1]]
[[0 0 0 0]
 [0 0 0 0]]


Creating a random sampling based on *uniform distribution* of a given shape

In [44]:
print(np.random.rand(2,3))   #random values between 0 and 1 of shape (2,3)

[[0.48733212 0.72900482 0.92676272]
 [0.35095981 0.75504823 0.43761832]]


Creating a random sampling based on *standard normal distribution* of given shape

In [45]:
print(np.random.randn(2,3))   #random values between -1 and 1 of shape (2,3)

[[ 0.85693999 -1.76335877  0.05692101]
 [ 0.97323477  0.91243777  0.09809171]]
